In [2]:
import numpy as np

In [4]:
a = np.arange(15).reshape(3,5)
print(a.shape)
print(a.ndim)
print(a.dtype.name)
print(a.itemsize)  #size in bytes of each element
print(a.size)

(3, 5)
2
int64
8
15


In [20]:
print((np.array([1,2,3,4,5,6]).reshape(2,3))[:,2])   #print 2 column of the 2-d array created with reshape

[3 6]


In [5]:
a=np.array([[2,3,4],[1,7,9]])
print(a.ndim)
b= np.array([1.2,3.5,5.1])
print(b.dtype)

2
float64


In [6]:
c = np.array([[1,2],[3,4]], dtype=np.complex128)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [4]:
#np.zeros, np.ones, np.empty, np.eye, np.indices, np.diag
a=np.zeros((3,4))
b= np.ones((2,3,4))
c = np.empty((6))
print(a)
print(b)
print(c)
print()
d = np.ones_like(c)
print(d)
print("-----")
print(np.eye(5))   #Identity matrix

print(np.indices((3,3)))
print(np.diag([1,2,3,4]))  #Matrix with diagonal elements 1,2,3,4
print(np.diag(a))  #returns the diagonal elements of b

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[1. 1. 1. 1. 1. 1.]

[1. 1. 1. 1. 1. 1.]
-----
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[0. 0. 0.]


In [10]:
np.arange(10,30,3)   #first, last, step

array([10, 13, 16, 19, 22, 25, 28])

In [11]:
np.linspace(10,30,8)   #linspace last argument is no of elements we want instead of step

array([10.        , 12.85714286, 15.71428571, 18.57142857, 21.42857143,
       24.28571429, 27.14285714, 30.        ])

In [3]:
np.ones((4,5)).ravel()   #flatten

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [12]:
from numpy import pi
import math
assert math.pi == pi
x=np.linspace(0, 2* pi, 100)

In [14]:
#import sys
#np.set_printoptions(threshold=sys.maxsize)    -- print all numbers to the screen and don't just print the corners when too large

In [7]:
a=np.array([20,30,40,50])
b=np.arange(4)
c = a -b
print(c)
print(b**2)
print(10 * np.sin(a))
print(a < 35)

#Create 2d array with random values
from numpy.random import default_rng
default_rng(42).random((2,3))



[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]


array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235]])

In [10]:
### Copying
a= np.array([1,2,3,4,5,6])
#b= a[:2]
#b += 1   #a[:2] is affected
b =a[:2].copy()

In [12]:
### Matrix multiplication vs Element-wise multiplication
a = np.array([[1,2],[3,4]])
b= np.array([[3,4],[5,6]])
print(a @ b)
print(a * 3)
print(a*b)

[[13 16]
 [29 36]]
[[ 3  6]
 [ 9 12]]
[[ 3  8]
 [15 24]]


In [19]:
### np.r_ and np.c_

c=np.r_[np.array([1,2,3]),0,0, np.array([4,5,6])]  #concatenate
print(c)
c= np.r_[-1:1:6j,5,6]   #when start:stop:stepj -i.e imaginary number for step then start, stop, number of points desired
print(c)

#string first argument specify the axis to concatenate along or minimum number of dimensions to force entries into
a = np.array([[1,2,3],[3,4,5]])
c = np.r_['-1',a,a] #concatenate along last axis
print(c)
print(np.r_['0',a,a]) #concatenate along 1st axis i.e rows in 2 dim case
print(np.r_['0,3',a,a]) #concatenate along 1st axis in 3 dimensions

[1 2 3 0 0 4 5 6]
[-1.  -0.6 -0.2  0.2  0.6  1.   5.   6. ]
[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]
[[[1 2 3]
  [3 4 5]]

 [[1 2 3]
  [3 4 5]]]


In [8]:
rng=np.random.default_rng()
np.c_[rng.integers(10,50,5), [1,2,3,4,5]]  #concatenate along 2nd axis (columns)

array([[44,  1],
       [37,  2],
       [38,  3],
       [26,  4],
       [10,  5]])

In [7]:
##universal functions
B = np.arange(3)
print("exp:", np.exp(B))
print("sqrt:", np.sqrt(B))

#argmax, max, cov, sum, mean, median, mode, std, maximum(element-wise max of 2 arrays), any, average

exp: [1.         2.71828183 7.3890561 ]
sqrt: [0.         1.         1.41421356]


In [9]:
(np.arange(5) >2)

array([False, False, False,  True,  True])

In [10]:
#astype

np.arange(10,30,4).astype("float64")

array([10., 14., 18., 22., 26.])

In [3]:
#transpose

arr_3d = np.ones((2,3,4))
transposed = np.transpose(arr_3d, (1,0,2))  #swap 0th and 1st dimension/axis
print(transposed.shape)

(3, 2, 4)


In [5]:
arr_3d.shape

(2, 3, 4)

In [4]:
from numpy.random import default_rng
default_rng().integers(3,20,12).reshape(3,4)

array([[17, 19,  3, 10],
       [11, 14, 12, 14],
       [18, 15, 14, 18]])

In [5]:
#np.permutation
rng = default_rng(seed=42)
a = rng.integers(2,20,12)
indices = rng.permutation(5)
print(f'a: {a}  \nindices: {indices}  \na[indices]: {a[indices]}')

a: [ 3 15 13  9  9 17  3 14  5  3 11 19]  
indices: [2 4 0 3 1]  
a[indices]: [13  9  3  9 15]


In [6]:
arr=np.array(["A","B","C"])
arr[[rng.integers(0,2,10)]]

array([['B', 'A', 'B', 'A', 'B', 'A', 'A', 'B', 'B', 'B']], dtype='<U1')

In [7]:
arr[[1,0,2,1]]

array(['B', 'A', 'C', 'B'], dtype='<U1')

In [3]:
arr = np.array([ [10,20,30,11],
                [40,95,50,4],
                [50,45,85,2.5]])

maxnum = np.max(arr)
max_of_each_col = np.max(arr, axis=0)   #operation moves down the rows
max_of_each_row = np.max(arr, axis=1)   #operation moves across the columns

arr.shape, maxnum, max_of_each_col, max_of_each_row

((3, 4), np.float64(95.0), array([50., 95., 85., 11.]), array([30., 95., 85.]))

In [4]:
arr.reshape(-1, 4)   #reshape (-1 ... numpy figures out the exact dimension (rows in this case)

array([[10. , 20. , 30. , 11. ],
       [40. , 95. , 50. ,  4. ],
       [50. , 45. , 85. ,  2.5]])

In [5]:
arr.shape[0]

3

In [9]:
#np.triu np.tril

A= np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

print(np.triu(A))
print()
print(np.triu(A,k=1))
print(np.triu(A,k=-1)) #== np.tril(A, k=1)
print(np.tril(A,k=1))

[[1 2 3]
 [0 5 6]
 [0 0 9]]

[[0 2 3]
 [0 0 6]
 [0 0 0]]
[[1 2 3]
 [4 5 6]
 [0 8 9]]
[[1 2 0]
 [4 5 6]
 [7 8 9]]
